### ISSUE TITLE
Any chance to add support for the new bridge / API (v6)?

### ISSUE THREAD

**Issue by odelma** [ojarva/python-ledcontroller#12]
Hi,

there is now some documentation available of the new wifi bridge / api: http://www.limitlessled.com/dev/ It would be great to see this supported as well :smile:

**Comment by ojarva** [comment]
I doubt developing functional and working support for that is possible solely based on the documentation. I don't have new bridge and I have currently no need to buy one.

**Comment by odelma** [comment]
No worries, there are nowadays several libraries available that support the new api 😄
