### ISSUE TITLE
Easybulb cloud API support

### ISSUE THREAD

**Issue by Zulex** [ojarva/python-ledcontroller#9]
Hello,

Library is working great! Got one feature request. The library seems to use the home ip and default port for sending commands. This way it can't be used outside the network. Changing te ip only doesn't work because using commands over internet requires communicating with the cloudserver and verifying with mac address of the wifi box. 

Some more information here : http://easybulb.com/api/

I'll be trying to make this feature and send it as pull request, but due to my poor programming knowlegde it might take a while. If someone could look this up, it would be awesome

**Comment by ojarva** [comment]
Hi Zulex,
I don't have a wifi box that would use any internet service for controlling the lights. Personally I have no interest to develop this feature.

If you implement support for this, feel free to create a pull request. But beware that there will most probably be things you need to fix (regarding programming style, documentation, tests and so on). I'll give a detailed comments about those to the PR.

**Comment by ojarva** [comment]
Now that I actually checked the Easybulb API, I don't think this should be part of this `python-ledcontroller` library - it should be implemented as a separate library, possibly with the same user-facing API.
